---
kind: pipeline
name: default-s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: fetch
  image: ubuntu:18.04
  commands:
  - apt-get update
  - apt-get install -y git
  - git fetch --tags

- name: build
  pull: default
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: publish-tagged-image
  image: rancher/drone-images:docker-s390x
  volumes:
    - name: docker
      path: /var/run/docker.sock
  settings:
    build_args:
    - ARCH=s390x
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password_rancherlabs_dev
    repo: rancherlabs/longhornonz-longhorn-manager
    tag: "${DRONE_TAG}-s390x"
    username:
      from_secret: docker_username_rancherlabs_dev
  when:
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
